config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:new, :create, :show]
  resources :flights, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "flights#index"
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  self.primary_key = :code

  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id", inverse_of: "departure_airport"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id", inverse_of: "arrival_airport"

  before_validation :capitalize_code

  validates :code, presence: true, length: { is: 3 }, format: { with: /\A[A-Z]+\z/, message: "only allows uppercase letters" }

  private
    def capitalize_code
      self.code = code.upcase if code.present?
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
# not checking overlapping flights
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport", foreign_key: "departure_airport_id",
    inverse_of: "departing_flights"
  belongs_to :arrival_airport, class_name: "Airport", foreign_key: "arrival_airport_id",
    inverse_of: "arriving_flights"

  before_validation :capitalize_airports
  has_many :bookings

  validates :departure_airport_id, :arrival_airport_id, :departure_time, :arrival_time,
    presence: true
  validates :departure_airport_id, :arrival_airport_id, length: { is: 3 }
  validates :departure_airport_id, :arrival_airport_id,
    format: { with: /\A[A-Z]+\z/, message: "only allows uppercase letters" }
  validate :arrival_time_after_departure_time

  def arrival_airport_name
    arrival_airport.name
  end

  def departure_airport_name
    departure_airport.name
  end

  def departure_time_str
    departure_time.strftime("%Y-%m-%d %H:%M")
  end
  def departure_time_date_str
    departure_time.strftime("%Y-%m-%d")
  end

  private
    def capitalize_airports
      self.departure_airport_id = departure_airport_id.upcase if departure_airport_id.present?
      self.arrival_airport_id = arrival_airport_id.upcase if arrival_airport_id.present?
    end
    def arrival_time_after_departure_time
      return unless departure_time.present? && arrival_time.present?

      if arrival_time <= departure_time
        errors.add(:arrival_time, "must be after the departure time")
      end
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings/1 or /bookings/1.json
  def show
    @booking = Booking.find(params[:id])
  end

  # GET /bookings/new
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build
    number_of_passengers = params[:number].to_i
    number_of_passengers.times { @booking.passengers.build }
    # alt: @number = params[:number].to_i
    # then in _form:
    # <h3>Passengers</h3>
    # <div data-controller="passenger" data-passenger-initial-count="<%= @number %>">
    #   <div data-passenger-target="passenger">
    #     <!-- Initial passenger fields will be added here by JavaScript -->
    #   </div>
    #   <button data-action="click->passenger#addPassenger">Add passenger</button>

    #   <template data-passenger-target="template">
    #     <%= f.fields_for :passengers, Passenger.new, child_index: 'TEMPLATE_RECORD' do |p| %>
    #       <%= render 'passenger_fields', f: p %>
    #     <% end %>
    #   </template>
    # </div>
    #   js:
    # connect() {
    #   const initialCount = this.element.dataset.passengerInitialCount;
    #   for (let i = 0; i < initialCount; i++) {
    #     this.addPassenger();
    #   }
    # }

    # addPassenger(event) {
    #   if (event) event.preventDefault();

  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking, notice: "Booking was successfully created."
    else
      render :new
    end
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :number])
    end
end

app/controllers/flight_search_form.rb
class FlightSearchForm
  include ActiveModel::Model

  attr_accessor :arrival_airport_id, :departure_airport_id, :number, :departure_time, :error_message

  def initialize(params = {})
    @arrival_airport_id = params[:arrival_airport_id]
    @departure_airport_id = params[:departure_airport_id]
    @number = params[:number]
    @departure_time = params[:departure_time]
  end
  def valid_query?
    @arrival_airport_id.present? && @departure_airport_id.present? && @number.present? && @departure_time.present?
  end
  def incomplete_query?
    any_blank = @arrival_airport_id.blank? || @departure_airport_id.blank? || @number.blank? || @departure_time.blank?
    all_blank = @arrival_airport_id.blank? && @departure_airport_id.blank? && @number.blank? && @departure_time.blank?

    if any_blank && !all_blank
      @error_message = "Please fill in all fields."
      return true
    end

    false
  end
  def query
    {
      arrival_airport_id: @arrival_airport_id,
      departure_airport_id: @departure_airport_id,
      departure_time: @departure_time.to_date.beginning_of_day..@departure_time.to_date.end_of_day
    }
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    Rails.logger.debug "Params: #{params.inspect}"
    @flights = Flight.all
    @flight_search = FlightSearchForm.new(search_params[:flight_search] || {})
    Rails.logger.debug "FlightSearchForm: #{@flight_search.inspect}"
    @search_result = nil
    if @flight_search.valid_query?
      @search_result = @flights.where(@flight_search.query)
      Rails.logger.debug "Search Result: #{@search_result.inspect}"
    elsif @flight_search.incomplete_query?
      flash.now[:alert] = @flight_search.error_message
    end
  end

  private
    def search_params
      params.permit(flight_search: [:arrival_airport_id, :departure_airport_id, :number,
:departure_time])
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <% booking.passengers.each do |passenger| %>
    <p>
      <strong>Passenger:</strong>
      <%= passenger.name %>
      <br>
      <strong>Number:</strong>
      <%= passenger.number %>
    </p>
    <br>
    <br>
    <br>
  <% end %>
  <p>
    <strong>Flight:</strong>
    <br>
    <strong>Departure:</strong>
    <%= booking.flight.departure_airport.name %>
    <br>
    <strong>Arrival:</strong>
    <%= booking.flight.arrival_airport.name %>
    <br>
    <%= booking.flight.departure_time %>
    <br>
    <br>
    <br>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |f| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :flight_id %>

  <div>
    <strong>Departure Airport:</strong> <%= @flight.departure_airport_name %> <br>
    <strong>Arrival Airport:</strong> <%= @flight.arrival_airport_name %> <br>
    <strong>Departure Time:</strong> <%= @flight.departure_time_str %> <br>
  </div>

  <h3>Passengers</h3>
  <div data-controller="passenger">
    <div data-passenger-target="passenger">
      <%= f.fields_for :passengers do |p| %>
        <%= render 'passenger_fields', f: p %>
      <% end %>
    </div>
    <button data-action="click->passenger#addPassenger">Add passenger</button>

    <template data-passenger-target="template">
      <%= f.fields_for :passengers, Passenger.new, child_index: 'TEMPLATE_RECORD' do |p| %>
        <%= render 'passenger_fields', f: p %>
      <% end %>
    </template>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/_passenger_fields.html.erb
<div class="nested-fields">
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :number %>
    <%= f.telephone_field :number %>
  </div>
  <button data-action="click->passenger#removePassenger">Remove</button>
</div>

app/views/bookings/new.html.erb
<% content_for :title, "New booking" %>

<h1>New booking</h1>

<%= render "form", booking: @booking %>

<br>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @booking %>

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Departure airport:</strong>
    <%= flight.departure_airport_id %>
  </p>

  <p>
    <strong>Arrival airport:</strong>
    <%= flight.arrival_airport_id %>
  </p>

  <p>
    <strong>Departure time:</strong>
    <%= flight.departure_time %>
  </p>

  <p>
    <strong>Arrival time:</strong>
    <%= flight.arrival_time %>
  </p>

</div>

app/views/flights/index.html.erb
<% if flash[:alert] %>
  <p style="color: red"><%= flash[:alert] %></p>
<% end %>

<% content_for :title, "Flights" %>

<h1>Flights</h1>

<%= form_with model: @flight_search, url: flights_path, method: :get, scope: :flight_search, local: true do |f| %>
  <div>
    <%= f.label :departure_airport_id, "Select Departure Airport" %>
    <%= f.collection_select :departure_airport_id, @flights.select(:departure_airport_id).distinct.order(:departure_airport_id), :departure_airport_id, :departure_airport_name, prompt: "Select Departure Airport" %>
  </div>
  <div>
    <%= f.label :arrival_airport_id, "Select Arrival Airport" %>
    <%= f.collection_select :arrival_airport_id, @flights.select(:arrival_airport_id).distinct.order(:arrival_airport_id), :arrival_airport_id, :arrival_airport_name, prompt: "Select Arrival Airport" %>
  </div>
  <div>
    <%= f.label :number, "Select Passenger Count" %>
    <%= f.collection_select :number, (1..4).to_a, :to_s, :to_s, prompt: "Select passenger count" %>
  </div>
  <div>
    <%= f.label :departure_time, "Departure Date" %>
    <%= f.select :departure_time, options_from_collection_for_select(@flights.select("DISTINCT DATE(departure_time) AS departure_date").order("departure_date"), :departure_date, :departure_date), prompt: "Select Date" %>
  </div>
  <%= f.submit "Search" %>
<% end %>

<% if @search_result.present? %>
  <h2>Search Results</h2>
  <div>
    <strong>Departure Airport:</strong> <%= @search_result.first.departure_airport_name %> <br>
    <strong>Arrival Airport:</strong> <%= @search_result.first.arrival_airport_name %> <br>
    <strong>Flights:</strong>
  </div>

  <%= form_with url: new_booking_path, method: :get do |f| %>
    <%= f.collection_radio_buttons :flight_id, @search_result, :id, :departure_time_str %>
    <%= f.hidden_field :number , value: @flight_search.number %>
    <%= f.submit "Book Flight" %>
  <% end %>
<% elsif !@search_result.nil? %>
  <p>No search results found.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>